spring.application.name=studentManagementSystem
spring.datasource.url=${DBPG_URL}
spring.datasource.username=${DBPG_USERNAME}
spring.datasource.password=${DBPG_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
